server:
  port: 8080
spring:
  application:
    name: skipe-demo
  redis:
    port: 6379
    host: 192.168.136.128
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:3306/spike?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
